# Example configuration for VAE training - Subject 02
data_config:
  data_root: "/gpfs/projects/bsc88/speech/research/scripts/Lucas/bp_prediction/data"
  subject: "S02"  # Different subject
  session: "Session1"
  sequence_length: 3
  pattern_offsets: [-7, 0, 3]
  bp_normalization: [40.0, 200.0]
  frame_normalization: "minmax"
  return_metadata: false
  force_reload: false

model_config:
  model_type: "vae"
  input_channels: 1
  input_height: 64
  input_width: 64
  latent_dim: 128
  hidden_dims: [32, 64, 128, 256]
  activation: "relu"
  dropout_rate: 0.2
  use_batch_norm: true

training_config:
  num_epochs: 100
  learning_rate: 0.001
  batch_size: 32
  optimizer: "adam"
  adam_betas: [0.9, 0.999]
  weight_decay: 1e-5
  vae_beta: 1.0
  use_scheduler: true
  scheduler_type: "cosine"
  use_mixed_precision: true
  grad_clip_norm: 1.0
  early_stopping_patience: 15
  early_stopping_min_delta: 1e-4
  output_dir: "experiments"
  save_every_n_epochs: 10
  use_wandb: true
  project_name: "bp_prediction_vae_s02"
  wandb_mode: "offline" 